FROM --platform=linux/amd64 python:3.11-slim
EXPOSE 8501
WORKDIR /app
RUN apt-get update && apt-get install -y
COPY requirements.txt ./requirements.txt
RUN pip install -r requirements.txt
COPY . .
CMD streamlit run app.py --server.enableCORS false --server.enableXsrfProtection false

# docker buildx build --platform linux/amd64 --output type=docker -t genai-rag-cost-estimator-lnx .