FROM --platform=linux/amd64 public.ecr.aws/lambda/python:3.9

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY lib/ lib/
COPY app.py app.py

CMD [ "app.lambda_handler"]